# Generated by Django 3.2.13 on 2022-06-19 16:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_district', models.BooleanField(default=False)),
                ('is_subdiv', models.BooleanField(default=False)),
                ('is_circle', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('circle_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('circle_name', models.CharField(max_length=40)),
                ('circle_name_hn', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'circle',
                'ordering': ['circle_id'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=40)),
                ('dist_name_hn', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'district',
                'ordering': ['dist_id'],
            },
        ),
        migrations.CreateModel(
            name='SubDiv',
            fields=[
                ('subdiv_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('subdiv_name', models.CharField(max_length=20)),
                ('subdiv_name_hn', models.CharField(max_length=20)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.district')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subdiv',
                'ordering': ['subdiv_id'],
            },
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_name', models.CharField(max_length=40)),
                ('panchayat_name_hn', models.CharField(max_length=40)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.circle')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.district')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'panchayat',
                'ordering': ['panchayat_name'],
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.district'),
        ),
        migrations.AddField(
            model_name='circle',
            name='subdiv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subdiv'),
        ),
        migrations.AddField(
            model_name='circle',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
