# Generated by Django 3.2.13 on 2022-06-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
